version: "3"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: cxp
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        tty: true
        ports:
            - "8000:8000"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

    vue:
        build:
            context: ./resources/vue-client
            dockerfile: Dockerfile
        image: vue_app
        container_name: vue_app
        restart: unless-stopped
        tty: true
        ports:
            - "5174:5174"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
